#!/bin/sh

update_fail() {
	./blank
	./say "DotUI installation files missing!"$'\n'"Please reinstall them to the SD card."$'\n\n'"Press any key to power off."
	read -n1 < /dev/input/event0
	sleep 1
	while true; do
		sync && poweroff && sleep 10
	done
}

# {
	
DIR=/mnt/SDCARD/miyoo354/app
cd "$DIR"

export LD_LIBRARY_PATH=/lib:/config/lib:/customer/lib

SYSTEM_PATH=/mnt/SDCARD/.system
OLD_SYSTEM_PATH=/mnt/SDCARD/.system_old

if [ ! -f "/mnt/SDCARD/miyoo354/app/MiniUI.zip" ] || [ -z "$(./miniunz 2> /dev/null)" ] || [ "$(hexdump -n 4 -e '1/4 "%u"' "/mnt/SDCARD/miyoo354/app/MiniUI.zip" 2> /dev/null)" != "67324752" ]; then
	update_fail
fi

./blank

# figure out what we're doing here
if [ -d "$SYSTEM_PATH" ]; then
	./say "Updating DotUI"
	NOUN=Update
	JUST_UPDATED=1
	rm -rf "$OLD_SYSTEM_PATH"
	mv "$SYSTEM_PATH" "$OLD_SYSTEM_PATH"
else
	./say "Installing DotUI"
	NOUN=Installation
	JUST_INSTALLED=1
fi

# then do it
./miniunz -x -o "/mnt/SDCARD/miyoo354/app/MiniUI.zip" -d "/mnt/SDCARD/" && test -f "/mnt/SDCARD/.tmp_update/updater"
if [ $? -ne 0 ]; then
	if [ ! -z "$JUST_UPDATED" ]; then
		rm -rf "$SYSTEM_PATH"
		mv "$OLD_SYSTEM_PATH" "$SYSTEM_PATH"
	fi
	rm -rf "/mnt/SDCARD/.tmp_update"
	sync
	update_fail
fi

# post-install
POST_INSTALL=/mnt/SDCARD/.system/post-install.sh
if [ -f "$POST_INSTALL" ]; then
	if [ -n "$JUST_INSTALLED" ]; then
		"$POST_INSTALL"
	fi
	rm -f "$POST_INSTALL"
fi

# post-update
POST_UPDATE=/mnt/SDCARD/.system/post-update.sh
if [ -f "$POST_UPDATE" ]; then
	if [ -n "$JUST_UPDATED" ]; then
		"$POST_UPDATE"
	fi
	rm -f "$POST_UPDATE"
fi

# we're done here
./blank
./say "$NOUN complete"

rm -rf "$OLD_SYSTEM_PATH"
rm -rf /tmp/MainUI.old
mv MainUI /tmp/MainUI.old
rm -rf /mnt/SDCARD/miyoo354
sync

# } > /mnt/SDCARD/miyoo.txt 2>&1

# let's do this
/mnt/SDCARD/.tmp_update/updater
